gatewayProxies:
  gatewayProxy:
    service:
      type: ClusterIP
      extraAnnotations:
        cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "ingressgateway"}}}'
    kind:
      deployment:
        replicas: 2
    antiAffinity: true
