[book]
title = "Konomi Docs"
authors = ["Andrew Pratheepan", "Yong Lin Wang", "Daniel Wu", "Anthony Lai", "Patrick Nguyen"]
description = "Internal Documents"
src = "docs"
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
no-section-label = true
