version: '3.8'

services:
  # Disable the API for now until
  # we can figure out networking problems with
  # prisma and docker
  chronicle-api:
    container_name: chronicle-api
    image: chronicle-api:1.0.0
    env_file:
      - .env.development
    build:
      context: ./server
      target: development
      dockerfile: Dockerfile
    command: yarn start:docker
    ports:
      - 3001:3001
      - 5555:5555
      - 9229:9229
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - chronicle-database
      - mongo_replica
  chronicle-database:
    image: mongo:5
    container_name: mongodb
    env_file:
      - .env.development
    ports:
      - 27017:27017
  mongo_replica:
    build: ./mongo_replica
    env_file:
      - .env.development
    ports:
      - 27018:27018
  db_seed:
    build:
      context: ./server
      dockerfile: Seed.Dockerfile
    depends_on:
      - chronicle-database
      - mongo_replica
    env_file:
      - .env.development
