# echo -n 'mongodb-password' | gcloud secrets create chronicle-staging-mongodb-password --replication-policy="automatic" --data-file=-
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: chronicle-staging-mongodb-password-secret # name of both the ExternalSecret and the generated k8s secret
spec:
  backendType: gcpSecretsManager
  data:
    - key: chronicle-staging-mongodb-password # name of the GCP secret
      name: value # key name in the k8s secret
      version: latest
