# echo -n 'mongodb-url' | gcloud secrets create chronicle-staging-mongodb-url --replication-policy="automatic" --data-file=- --locations=us-west4
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: chronicle-staging-mongodb-url-secret # name of both the ExternalSecret and the generated k8s secret
spec:
  backendType: gcpSecretsManager
  data:
    - key: chronicle-staging-mongodb-url # name of the GCP secret
      name: value # key name in the k8s secret
      version: latest