# echo -n 'mongodb-password' | gcloud secrets create chronicle-staging-mongodb-password --replication-policy="automatic" --data-file=- 
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: chronicle-staging-mongodb-password-secret
spec:
  backendType: gcpSecretsManager
  data:
    - key: chronicle-staging-mongodb-password # name of the GCP secret
      name: mongodb-password # name of the 
      version: latest