# echo -n '{"value": "my-secret-value"}' | gcloud secrets create my-secret --replication-policy="automatic" --data-file=-
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-gcp-secret # name of both the ExternalSecret and the generated k8s secret
spec:
  backendType: gcpSecretsManager
  projectId: konomi-ai
  data:
    - key: my-secret # name of the GCP secret
      property: value # name of the field in the GCP secret to use
      name: secret-key # key name in the k8s secret
      version: latest # version of the GCP secret