name: mdbook

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'book.toml'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-mermaid: true
          mermaid-version: 0.12.1

      - run: mdbook-mermaid install
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: docs
          cname: docs.konomi.ai
