name: Format Codebase
on:
  pull_request:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Using NodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Running Prettier
        run: npm run prettier
