# https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
# https://cloud.google.com/iam/docs/configuring-workload-identity-federation#github-actions
name: Update Secrets in K8s
on:
  push:
    branches:
      - secrets-push
jobs:
  push-github-secret-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'chronicle-staging'
          location: 'us-east1'
      - id: 'get-pods'
        run: 'kubectl get pods'
      - name: Push DATABASE_URL k8s Secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'staging'
          secret-type: 'generic'
          secret-name: chronicle-staging-mongodb-url-secret
          data: ${{ secrets.DATABASE_URL }}
      - name: Push MONGODB_USER k8s Secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'staging'
          secret-type: 'generic'
          secret-name: chronicle-staging-mongodb-user-secret
          data: ${{ secrets.MONGODB_PASSWORD }}
      - name: Push MONGODB_PASSWORD k8s Secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'staging'
          secret-type: 'generic'
          secret-name: chronicle-staging-mongodb-password-secret
          data: ${{ secrets.MONGODB_PASSWORD }}
      - name: Push ACCESS_TOKEN_KEY k8s Secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'staging'
          secret-type: 'generic'
          secret-name: chronicle-staging-access-token-key-secret
          data: ${{ secrets.ACCESS_TOKEN_KEY }}
      - name: Push ACCESS_TOKEN_EXPIRY_KEY k8s Secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'staging'
          secret-type: 'generic'
          secret-name: chronicle-staging-access-token-expiry-key-secret
          data: ${{ secrets.ACCESS_TOKEN_EXPIRY_KEY }}
