name: Seed Database
on:
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Seed Staging DB
        uses: ameydev/gke-kubectl-action@v1.02
        env:
          PROJECT_ID: konomi-ai
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_K8S_SA }}
          CLUSTER_NAME: chronicle-staging
          ZONE_NAME: us-east1
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          args: apply -f infrastructure/kubernetes/staging/seed.yaml -n staging
